/**
 * Genotyping-by-sequencing is an approach for genotyping multiplexed
 * samples that comes from libraries generated by restriction enzymes.
 *
 * These classes help map and process the massive data sets.
 *
 */
package net.maizegenetics.gbs;

